const title = "Project Vlad";
const screens = "Simple, Complex, Interactive";
const screenPrice = 30;
const rollback = 60;
const fullPrice = 90;
const adaptive = true;
console.log(typeof title);
console.log(typeof fullPrice);
console.log(typeof adaptive);
console.log(screens.length);
console.log(screenPrice);
console.log(fullPrice);
console.log(screens.toLowerCase().split(", "));
console.log(90 * (60 / 100));